# Generated by Django 4.0.6 on 2022-08-10 04:47

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.AddField(
            model_name='account',
            name='account_option',
            field=models.CharField(choices=[('f', 'Fixed'), ('c', 'CurrentAccount')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='reward',
            name='nationality',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='reward',
            name='profile_picture',
            field=models.ImageField(null=True, upload_to='profile_pictures/'),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_status',
            field=models.CharField(choices=[('d', 'Debit'), ('c', 'Credit')], max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_type',
            field=models.CharField(choices=[('m', 'Mastercard'), ('v', 'Visacard')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='status',
            field=models.CharField(choices=[('read', 'Read'), ('unread', 'Unread')], max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('withdraw', 'Withdrawal'), ('depo', 'Deposit')], max_length=10, null=True),
        ),
    ]
