# Generated by Django 4.0.6 on 2022-08-26 10:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0002_delete_customer_account_account_option_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receipt_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('recipt_number', models.CharField(max_length=25, null=True)),
                ('total_Amount', models.IntegerField(default=0)),
                ('recipt_File', models.FileField(upload_to='wallet/')),
            ],
        ),
        migrations.RemoveField(
            model_name='account',
            name='account_option',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='receipt',
        ),
        migrations.AlterField(
            model_name='account',
            name='account_type',
            field=models.CharField(choices=[('f', 'Fixed'), ('c', 'CurrentAccount')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='reward',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Reward_transaction', to='wallet.transaction'),
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(null=True, upload_to='profile_pictures/'),
        ),
        migrations.DeleteModel(
            name='Receipts',
        ),
        migrations.AddField(
            model_name='receipt',
            name='account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Receipts_account', to='wallet.account'),
        ),
        migrations.AddField(
            model_name='receipt',
            name='transaction',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Receipts_transaction', to='wallet.transaction'),
        ),
    ]
